# Generated by Django 5.2.8 on 2025-11-28 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('telegram', 'Telegram Bot'), ('web', 'Web Form'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('reporter_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('pending', 'Pending Analysis'), ('advise', 'Advice Given'), ('report', 'Reported to Partner')], default='pending', max_length=20)),
                ('detected_location', models.CharField(blank=True, max_length=255, null=True)),
                ('chain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Screenshot/Image'), ('audio', 'Voice Note'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('derived_text', models.TextField(blank=True, null=True)),
                ('sha256_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_assets', to='cases.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
