# Generated by Django 5.2.9 on 2026-01-08 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='action',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('advise', 'Advice Given'), ('report', 'Reported to Authority')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='case_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='detected_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='risk_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram Bot'), ('web', 'Web Form'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['source', 'action'], name='cases_incid_source_e12734_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['risk_score', 'created_at'], name='cases_incid_risk_sc_9d504b_idx'),
        ),
    ]
