# Generated by Django 5.2.9 on 2026-01-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_incidentreport_action_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, help_text='Partner organization handling this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='jurisdiction',
            field=models.CharField(blank=True, db_index=True, help_text='Country/Region for partner visibility (auto-set from detected_location)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
