# Generated by Django 5.2.8 on 2026-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_incidentreport_assigned_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='chain_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
