# Generated by Django 5.2.8 on 2026-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_incidentreport_chain_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='contact_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='perpetrator_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
