# Generated by Django 6.0.2 on 2026-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_incidentreport_contact_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reasoning_log',
            field=models.JSONField(blank=True, default=list, help_text='Real-time log of agent artifacts'),
        ),
    ]
