# Generated by Django 5.2.9 on 2026-01-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('org_type', models.CharField(choices=[('NGO', 'Non-Governmental Organization'), ('LEA', 'Law Enforcement Agency'), ('GOV', 'Government Body'), ('LEGAL', 'Legal Aid Provider'), ('HEALTH', 'Healthcare Provider'), ('OTHER', 'Other')], default='NGO', max_length=20)),
                ('jurisdiction', models.CharField(db_index=True, help_text="Country or region this partner covers (e.g., 'Kenya', 'Nigeria')", max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-verified partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Organization',
                'verbose_name_plural': 'Partner Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Organization Admin'), ('RESPONDER', 'Case Responder'), ('VIEWER', 'Read-Only Viewer')], default='RESPONDER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='partners.partnerorganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner User',
                'verbose_name_plural': 'Partner Users',
            },
        ),
    ]
