# Generated by Django 5.2.8 on 2026-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='max_seats',
            field=models.PositiveIntegerField(default=5, help_text='Maximum team members allowed in this organization'),
        ),
    ]
