# Generated by Django 6.0.2 on 2026-02-20 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_incidentreport_contact_preference_and_more'),
        ('partners', '0003_partnerorganization_max_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='agent_persona',
            field=models.TextField(blank=True, help_text="Custom persona for this org's AI responder (e.g., 'Formal Legal', 'Empathetic NGO')"),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='is_agent_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI Response Assistant for this organization'),
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partneruser')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_notes', to='cases.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CLAIM', 'Claimed Case'), ('STATUS_CHANGE', 'Changed Status'), ('MEMBER_REMOVE', 'Removed Team Member'), ('ROLE_CHANGE', 'Updated Member Role')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='partners.partnerorganization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
