# Generated by Django 5.2.8 on 2025-11-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(default='telegram', max_length=20)),
                ('last_detected_location', models.CharField(blank=True, max_length=255, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=10, null=True)),
                ('cancelled_until', models.DateTimeField(blank=True, null=True)),
                ('awaiting_location', models.BooleanField(default=False)),
                ('pending_report_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20)),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='triage.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
