# Generated by Django 5.2.8 on 2025-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='cancelled_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
