# Generated by Django 5.2.8 on 2026-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', '-created_at'], name='triage_chat_session_482334_idx'),
        ),
    ]
