# Generated by Django 5.2.8 on 2026-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_chatmessage_triage_chat_session_482334_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_state',
            field=models.CharField(choices=[('IDLE', 'Waiting for input'), ('GATHERING', 'Gathering information'), ('ASKING_LOCATION', 'Waiting for location'), ('CONFIRMING', 'Asking for confirmation'), ('PROCESSING', 'Processing report')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='gathered_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('discord', 'Discord'), ('web', 'Web Portal')], default='telegram', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('chat_id', 'platform')},
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chat_id', 'platform'], name='triage_chat_chat_id_52ddb1_idx'),
        ),
    ]
