# Generated by Django 5.2.8 on 2026-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_add_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='case_creation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='gathered_required_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_ai_instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='required_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
