# Generated by Django 5.2.8 on 2026-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchlog',
            name='brevo_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
