# Generated by Django 5.2.8 on 2026-01-13 17:58

import django.db.models.deletion
import django_editorjs2.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerinvite'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author_organization',
            field=models.ForeignKey(blank=True, help_text='Partner organization authoring this article (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='partners.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_editorjs2.fields.EditorJSField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='publications.tag'),
        ),
    ]
