# Generated by Django 5.2.8 on 2025-11-28 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('jurisdiction_level', models.CharField(choices=[('city', 'City'), ('state', 'State/Province'), ('country', 'Country'), ('regional', 'Regional')], default='city', max_length=20)),
                ('jurisdiction_name', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Tags like 'Cybercrime', 'Domestic Violence', 'Women Safety'", size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher priority contacts are preferred (1-10)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Authority Contact',
                'verbose_name_plural': 'Authority Contacts',
                'ordering': ['-priority', 'jurisdiction_name'],
            },
        ),
    ]
