# Generated by Django 5.2.9 on 2026-01-08 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritycontact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='authoritycontact',
            name='jurisdiction_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authoritycontact',
            name='priority',
            field=models.IntegerField(default=1, help_text='Higher priority contacts are preferred (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='authoritycontact',
            index=models.Index(fields=['is_active', 'jurisdiction_name'], name='directory_a_is_acti_34f2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='authoritycontact',
            index=models.Index(fields=['is_active', '-priority'], name='directory_a_is_acti_c386f7_idx'),
        ),
    ]
