# Generated by Django 5.2.8 on 2025-11-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_authoritycontact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritycontact',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags like 'Cybercrime', 'Domestic Violence', 'Women Safety'"),
        ),
    ]
